### ISSUE TITLE
Instead of a text indicating the mode, I get `$(vi_mode_prompt_info)`

### ISSUE THREAD

**Issue by ecesar88** [Nyquase/vi-mode#4]
Hello! Installed the plugin yesterday using zplug  and the mode indicator isn't working very well.
![image](https://user-images.githubusercontent.com/37763819/143447541-dee94af3-f13a-4219-b10d-5f1c77a0a16a.png)
As you can see in the screenshot, it shows `$(vi_mode_prompt_info)`. I tried uninstalling and installing the plugin again but it didn''t work. Is there any option to disable it or a quick fix for this? **I'm using the starship prompt**.

**Comment by Nyquase** [comment]
Hello ! That `$(vi_mode_prompt_info)` is the name of the function that prints the mode. It is a simple feature of zsh called [Command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html) so that bug is most probably due to the starship prompt you are using.
Unfortunately, I do not plan to support starship yet, it does look interesting though. As of now I can only recommend to try and make it work yourself, shell is pretty quick to learn :)
